### ISSUE TITLE
Add an icon for .csv files

### ISSUE THREAD

**Issue by gj1118** [oivva/st-file-icons#13]
I work with CSV files a lot.It would be a lot of help if you can provide an icon for CSV file types. Right now, there are no CSV icons for CSV file types. 

![image](https://cloud.githubusercontent.com/assets/473101/19655415/c82a5ee8-99e9-11e6-9a9d-418371c9a11e.png)

Expected Behavior
A CSV icon should be displayed for the CSV file types

Current Behavior
Uses the default icon for CSV file types

**Comment by michaelblyons** [comment]
Can you also add an activating scope for `text.csv`?

**Comment by oivva** [comment]
@michaelblyons For `.csv` icon you have to install [Advanced CSV](https://packagecontrol.io/packages/Advanced%20CSV) package. Also see [Wrong Icons](https://github.com/oivva/sublime-file-icons#wrong-icons) section.

**Comment by michaelblyons** [comment]
> Can you tell me what syntax adds this scope?

I [forked Advanced CSV][fork] to make the scopes consistent with the ST3 [scope guidelines][scope]<sup>1</sup>. I haven't set up a PR, though, because I've never done a PR with such big changes and I don't know how well it would be received.

<sup>1</sup>Which means better Boxy support. ;-)

[fork]: https://github.com/michaelblyons/SublimeSyntax-CSV/tree/comma-push
[scope]: https://www.sublimetext.com/docs/3/scope_naming.html

**Comment by oivva** [comment]
@michaelblyons Done :smile: It's present in 2.2.0 :wink:
