### ISSUE TITLE
Conflict with Seti_ui and Javascript (Babel) (*.js and *.jsx)

### ISSUE THREAD

**Issue by infantito** [oivva/st-file-icons#6]
I have problems with JSX:
I'm using SETI_UI, Babel (Javascript (Babel)) and zz-files-icons.

* When setting my files with Javascript (babel) js syntax and .jsx icon JSX zz-files-icons does not catch.
* DockerFile icon is not displayed
* Add icon webpack as ATOM (webpack.config)
* Add icon node_modules (node.js)
* It would be good server.js files have the icon of a server or nodejs

Very good plugin. +10 (1 star)

**Comment by oivva** [comment]
> When setting my files with Javascript (babel) js syntax and .jsx icon JSX zz-files-icons does not catch

That's why custom themes should not contains preferences for icons. You can request support of this package from `SETI_UI` developer. Current implementation adds `jsx` icon only for [JSX](https://packagecontrol.io/packages/JSX) package. [Babel](https://github.com/babel/babel-sublime) plugin have to provide another scope for `jsx` files but not `source.js` for all.

> DockerFile icon is not displayed

Have you installed [Dockerfile Syntax Highlighting](https://packagecontrol.io/packages/Dockerfile%20Syntax%20Highlighting) package? More info [here](https://github.com/oivva/zz-file-icons#wrong-icons).

> Add icon webpack as ATOM (webpack.config)

I'll add it in the next release.

> Add icon node_modules (node.js)

It's not possible. Sublime Text has no API for that.

> It would be good server.js files have the icon of a server or nodejs

Under consideration. Vote for it.
